num1=float(input("Enter First Number"))
num2=float(input("Enter Second Number"))
print(f"The sum of {num1} and {num2} is", num1 + num2)
print(f"The quotient of {num1} and {num2} is", num1/num2)
print(f"The difference of {num1} and {num2} is", num1 - num2)
print(f"The product of {num1} and {num2} is", num1 * num2)
print(f"The modulus of {num1} and {num2} is", num1 % num2)